####################################################
#
# Welcome to CVfolio Jekyll Template
#
# Product Link : https://themeix.com/product/cvfolio-jekyll-template/
# Version : v1.0.0
#
####################################################

# Site settings
title: "Möhl Data Services"
#email: "themeix@gmail.com"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moehl-data-services.de" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/moehl-data-services-logo.png
description: "Christoph Möhl: Data Scientist, Python Entwickler, Data Engineer"
keywords: "freelance, Python, consulting, Data Engineer, Beratung, Bildanalyse, Imageprocessing, Image Analysis, Bonn, Köln, Germany, Deuschland, "
#mailclimp: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=4784863884"
#facebook: https://facebook.com/themeix
#instagram: https://instagram.com/themeix
#twitter: https://twitter.com/themeix_com
#pinterest: https://pinterest.com/themeix

# Disqus Comments
#disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    #shortname: documenter-jekyll


# Build settings
markdown: kramdown
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-paginate

collections:
  services:
    output: true
    permalink: /service/:path/
#   portfolios:
#     output: true
#     permalink: /portfolio/:path/
#   jobs:
#     output: true
#     permalink: /job/:path/

# feed:
#   collections:
#     posts:
#       path: "/index.xml"
