name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # or master before October 2020

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Build website
    - name: build website artifacts
      uses:  jerryjvl/jekyll-build-action@v1
     
    - name: "path"
      run: pwd ${{ vars.GITHUB_WORKSPACE }}

    - name: "listdir"
      run: ls ${{ vars.GITHUB_WORKSPACE }}

    # Copy Website artifacts to server
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp://www352.your-server.de
        username: moehlf
        password: ${{ secrets.ftp_password }}
        local-dir: ./_site/
        server-dir: public_html/ 

    - name: "error"
      run: cat ./_site/.ftp-deploy-sync-state.json