name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # or master before October 2020

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    
    - name: create downloads folder
      run: mkdir ./downloads
    
    - name: render agb pdf download pdf
      uses: docker://pandoc/latex:2.9
      with:
        args: --output ./downloads/agb_moehl_data_services.pdf agb_moehl_data_services.md

    - name: build website artifacts
      uses:  jerryjvl/jekyll-build-action@v1

    - name: render german cv download pdf
      uses: docker://pandoc/latex:2.9
      with:
        args: -V color-links=True -V margin-left=1.9cm -V margin-right=1.9cm -V margin-bottom=1.9cm -V margin-top=1.9cm --output ./downloads/cv_moehl_de.pdf ./_site/cv_de.html

    - name: render international cv download pdf
      uses: docker://pandoc/latex:2.9
      with:
        args: -V color-links=True -V margin-left=1.9cm -V margin-right=1.9cm -V margin-bottom=1.9cm -V margin-top=1.9cm --output ./downloads/cv_moehl_en.pdf ./_site/cv_en.html    
  
    - name: build website artifacts 2nd time to include downloads
      uses:  jerryjvl/jekyll-build-action@v1
 
    - name: Install lftp
      run: sudo apt install lftp

    - name: upload website artifacts
      run: lftp -c "set ssl:verify-certificate false; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }}; mirror -R _site public_html"

    

    